# =============================================================================
# DATABASE-DRIVEN SENTENCE CLASSIFICATION CLIENT
# =============================================================================
# This script reads pre-filtered and categorized sentences from the
# 'clean_web_data.db' (generated by filter_database.py) and sends them
# to the classification server for NLI analysis.
#
# It implements:
# 1. Multi-stage hypothesis classification (Policy, Notional, Position, PnL)
# 2. Early-exit strategy for maximum efficiency
# 3. Robust resumable processing with intermediate checkpoints
# 4. Multi-machine support via chunking
# =============================================================================

import requests
import sqlite3
import json
import sys
import argparse
import pandas as pd
import time
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import List, Dict, Tuple, Any
from pathlib import Path

# =============================================================================
# CONFIGURATION
# =============================================================================

# Database path for the clean, filtered data
DB_PATH = "clean_web_data.db"

# API endpoint of your classification server
SERVER_BASE_URL = "http://127.0.0.1:5000"
CLASSIFY_ENDPOINT = f"{SERVER_BASE_URL}/classify"
INFO_ENDPOINT = f"{SERVER_BASE_URL}/info"

# Results configuration
RESULTS_TABLE = "classification_results"
RESULTS_PARQUET_TEMPLATE = "classification_results_chunk_{}.parquet"

# Processing configuration
SAVE_INTERVAL_FILINGS = 500  # Save checkpoint every N filings
MAX_WORKERS = 2
BATCH_SIZE = 32

# Google Drive configuration
IS_COLAB = Path("./drive/MyDrive/").exists()
DRIVE_PATH = "./drive/MyDrive/db"

# Map derivative types from the DB to the 'term' for the model
DERIVATIVE_TYPE_TO_TERM_MAP = {
    "ir_matches": "interest rate derivative",
    "fx_matches": "foreign exchange derivative",
    "cp_matches": "commodity derivative",
    "eq_matches": "equity derivative",
}

# This needs to be in sync with the server's STAGE_HYPOTHESES_MAP
STAGE_HYPOTHESES_MAP = {
    "policy": ["H1_Policy"],
    "notional": ["H3_Notional"],
    "position": ["H2_Existence", "H4_PnL_Impact"],
}

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================


def prepare_results_for_parquet(results: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Normalize results to a flat, consistent structure for Parquet storage.
    Ensures all results have the same schema, preventing write errors.
    """
    normalized = []
    for r in results:
        normalized.append(
            {
                "url": r.get("url"),
                "cik": r.get("cik"),
                "year": r.get("year"),
                "found_policy": bool(r.get("found_policy", False)),
                "found_existence": bool(r.get("found_existence", False)),
                "found_notional": bool(r.get("found_notional", False)),
                "found_pnl": bool(r.get("found_pnl", False)),
                "status": str(r.get("status", "unknown")),
                "duration_s": float(r.get("duration_s", 0.0)),
                "error_message": (
                    str(r.get("error_message")) if r.get("error_message") else None
                ),
            }
        )
    return normalized


def save_chunk_to_parquet(
    all_results: List[Dict[str, Any]], output_parquet_path: str
) -> int:
    """
    Saves results to a Parquet file with proper schema normalization.
    Returns the number of rows saved.
    """
    if not all_results:
        return 0

    try:
        normalized_results = prepare_results_for_parquet(all_results)
        df = pd.DataFrame(normalized_results)
        df.to_parquet(output_parquet_path, index=False)
        return len(df)
    except Exception as e:
        print(f"    ❌ Error saving to Parquet file {output_parquet_path}: {e}")
        return 0


def get_already_processed_in_parquet(
    output_parquet_file: str,
) -> Tuple[set, List[Dict]]:
    """
    Check if a parquet checkpoint exists and load already-processed URLs.
    Returns: (set of processed URLs, list of existing results)
    """
    if not Path(output_parquet_file).exists():
        return set(), []

    try:
        df = pd.read_parquet(output_parquet_file)
        processed_urls = set(df["url"].tolist())
        existing_results = df.to_dict("records")
        return processed_urls, existing_results
    except Exception as e:
        print(f"    ⚠️ Could not read parquet checkpoint: {e}")
        return set(), []


def ping_server() -> Tuple[int, int]:
    """
    Pings the classification server's /info endpoint to dynamically configure
    MAX_WORKERS and BATCH_SIZE based on server GPU RAM.
    """
    print(f"Attempting to connect to server at {INFO_ENDPOINT}...")
    try:
        response = requests.get(INFO_ENDPOINT, timeout=10)
        response.raise_for_status()
        server_info = response.json()
        print("✅ Successfully connected to the classification server.")

        if server_info.get("gpu_available"):
            gpu_ram = server_info.get("total_ram_gb", 0)
            print(
                f"   -> Server has GPU: {server_info.get('gpu_name')} with {gpu_ram:.2f} GB RAM"
            )
            # Scale workers and batch size based on GPU RAM
            if gpu_ram > 20:  # A100, H100, etc.
                max_workers = 16
                batch_size = 128
            elif gpu_ram > 14:  # T4, P100, V100
                max_workers = 8
                batch_size = 64
            elif gpu_ram > 6:  # Smaller GPUs
                max_workers = 4
                batch_size = 32
            else:
                max_workers = 2
                batch_size = 16
        else:
            print("   -> ⚠️ Server has no GPU.")
            max_workers = 2
            batch_size = 16

        print(
            f"   -> Dynamically configured: MAX_WORKERS={max_workers}, BATCH_SIZE={batch_size}"
        )
        return max_workers, batch_size

    except requests.exceptions.RequestException as e:
        print(f"❌ Could not connect to server.")
        print(f"   Error: {e}")
        print("   Please ensure the classification server is running and accessible.")
        return MAX_WORKERS, BATCH_SIZE


# =============================================================================
# DATABASE FUNCTIONS
# =============================================================================


def setup_database():
    """Creates the results table in the database if it doesn't exist."""
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute(
        f"""
        CREATE TABLE IF NOT EXISTS {RESULTS_TABLE} (
            url TEXT PRIMARY KEY,
            cik INTEGER,
            year INTEGER,
            found_policy BOOLEAN,
            found_existence BOOLEAN,
            found_notional BOOLEAN,
            found_pnl BOOLEAN,
            status TEXT,
            duration_s REAL,
            error_message TEXT
        )
        """
    )
    c.execute(f"CREATE INDEX IF NOT EXISTS idx_res_url ON {RESULTS_TABLE} (url)")
    conn.commit()
    conn.close()


def get_unprocessed_filings(
    resumed_urls: set = None,
) -> List[Tuple[str, int, int]]:
    """
    Fetches filings from 'report_data' that are NOT yet in 'classification_results'.
    This makes the script resumable.
    """
    if resumed_urls is None:
        resumed_urls = set()

    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()

    # Get URLs already processed in the main DB table
    c.execute(f"SELECT url FROM {RESULTS_TABLE}")
    db_processed_urls = {row[0] for row in c.fetchall()}

    # Combine with URLs from a resumed parquet file
    all_processed_urls = db_processed_urls.union(resumed_urls)

    # Fetch all filings and filter in memory
    query = """
        SELECT rd.url, rd.cik, rd.year
        FROM report_data rd
    """
    c.execute(query)
    all_filings = c.fetchall()
    conn.close()

    # Filter out processed filings
    filings = [f for f in all_filings if f[0] not in all_processed_urls]
    return filings


def get_sentences_for_filing(url: str) -> Dict[str, List[str]]:
    """
    Retrieves all categorized sentences for a given filing URL.
    """
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute(
        "SELECT ir_matches, fx_matches, cp_matches, eq_matches FROM derivative_type_matches WHERE url=?",
        (url,),
    )
    result = c.fetchone()
    conn.close()

    if not result:
        return {}

    (ir_json, fx_json, cp_json, eq_json) = result
    sentences_by_type = {
        "ir_matches": json.loads(ir_json) if ir_json else [],
        "fx_matches": json.loads(fx_json) if fx_json else [],
        "cp_matches": json.loads(cp_json) if cp_json else [],
        "eq_matches": json.loads(eq_json) if eq_json else [],
    }
    return sentences_by_type


# =============================================================================
# CLASSIFICATION WORKER
# =============================================================================


def classify_sentences_for_stage(
    sentences: List[str], term: str, year: int, stage: str
) -> Dict[str, bool]:
    """
    Sends a list of sentences to the classification server and checks for
    'entailment' for the hypotheses associated with that stage.

    Returns: A dictionary mapping hypothesis IDs to a boolean indicating if entailment was found.
    """
    if not sentences:
        return {}

    # Initialize results for all hypotheses in this stage
    hypotheses_in_stage = STAGE_HYPOTHESES_MAP.get(stage, [])
    stage_results = {hypo_id: False for hypo_id in hypotheses_in_stage}

    for i in range(0, len(sentences), BATCH_SIZE):
        batch = sentences[i : i + BATCH_SIZE]
        payload = {
            "term": term,
            "stage": stage,
            "sentences": batch,
            "year": year,
        }
        try:
            response = requests.post(CLASSIFY_ENDPOINT, json=payload, timeout=60)
            response.raise_for_status()
            results = response.json().get("results", [])

            for result in results:
                classifications = result.get("classifications", {})
                for hypo_id in hypotheses_in_stage:
                    if classifications.get(hypo_id) == "entailment":
                        stage_results[hypo_id] = True
        except requests.exceptions.RequestException as e:
            print(f"    ❌ API call failed for term '{term}': {e}")
            return {}  # Return empty dict on error

    return stage_results


def process_filing(filing_info: Tuple[str, int, int]) -> Dict[str, Any]:
    """
    Worker function to process a single filing with early-exit logic.

    Returns a result dictionary with findings and metadata.
    """
    url, cik, year = filing_info
    start_time = time.time()

    # Initialize result with all fields
    final_result: Dict[str, Any] = {
        "cik": cik,
        "year": year,
        "url": url,
        "found_policy": False,
        "found_existence": False,
        "found_notional": False,
        "found_pnl": False,
        "status": "processed",
        "error_message": None,
    }

    try:
        # 1. Get all categorized sentences for the filing
        sentences_by_type = get_sentences_for_filing(url)
        if not any(sentences_by_type.values()):
            final_result["status"] = "no_sentences"
            final_result["duration_s"] = round(time.time() - start_time, 2)
            return final_result

        # 2. STAGE 1: Notional Check (Highest Confidence, Early Exit)
        for category, term in DERIVATIVE_TYPE_TO_TERM_MAP.items():
            sentences = sentences_by_type.get(category, [])
            if not sentences:
                continue

            notional_results = classify_sentences_for_stage(
                sentences, term, year, "notional"
            )
            if notional_results.get("H3_Notional"):
                final_result["found_notional"] = True
                final_result["status"] = "found_notional_early"
                final_result["duration_s"] = round(time.time() - start_time, 2)
                return final_result  # EARLY EXIT

        # 3. STAGE 2: Position Check (if no notional found)
        for category, term in DERIVATIVE_TYPE_TO_TERM_MAP.items():
            sentences = sentences_by_type.get(category, [])
            if not sentences:
                continue

            position_results = classify_sentences_for_stage(
                sentences, term, year, "position"
            )
            if position_results.get("H2_Existence"):
                final_result["found_existence"] = True
            if position_results.get("H4_PnL_Impact"):
                final_result["found_pnl"] = True

        # 4. STAGE 3: Policy Check (run regardless, as it's a different type of evidence)
        for category, term in DERIVATIVE_TYPE_TO_TERM_MAP.items():
            sentences = sentences_by_type.get(category, [])
            if not sentences:
                continue

            policy_results = classify_sentences_for_stage(
                sentences, term, year, "policy"
            )
            if policy_results.get("H1_Policy"):
                final_result["found_policy"] = True

        # 5. Determine final status
        if final_result["found_existence"] or final_result["found_pnl"]:
            final_result["status"] = "found_position"
        elif final_result["found_policy"]:
            final_result["status"] = "found_policy_only"
        else:
            final_result["status"] = "no_evidence_found"

    except Exception as e:
        final_result["status"] = "error"
        final_result["error_message"] = str(e)

    final_result["duration_s"] = round(time.time() - start_time, 2)
    return final_result


# =============================================================================
# MAIN EXECUTION
# =============================================================================


def run_classification(total_chunks: int, chunk_index: int):
    """Main classification loop with intermediate checkpointing."""
    print("=" * 80)
    if total_chunks > 1:
        print(
            f"🚀 Starting DB Classification (Chunk Mode: {chunk_index}/{total_chunks})"
        )
    else:
        print("🚀 Starting DB Classification (Standalone Mode)")
    print("=" * 80)

    # Ping the server first to ensure it's available
    global MAX_WORKERS, BATCH_SIZE
    MAX_WORKERS, BATCH_SIZE = ping_server()
    if MAX_WORKERS == 0:  # Indicates a connection failure
        print("\nExiting due to server connection failure.")
        sys.exit(1)

    # 1. Define unique output file for this chunk
    output_parquet_file = RESULTS_PARQUET_TEMPLATE.format(chunk_index)

    # 2. Set up DB and handle resuming from Parquet file
    setup_database()
    parquet_processed_urls, existing_results = get_already_processed_in_parquet(
        output_parquet_file
    )

    if existing_results:
        print(f"🔄 Resuming from existing file: {output_parquet_file}")
        print(f"   -> Loaded {len(existing_results)} URLs from checkpoint.")
        all_chunk_results = existing_results
    else:
        all_chunk_results = []

    # Get filings to process (excluding those already in parquet and DB)
    filings_to_process = get_unprocessed_filings(resumed_urls=parquet_processed_urls)

    if not filings_to_process:
        print("✅ No new filings to process. Exiting.")
        sys.exit(0)

    # 3. Split workload for multi-machine processing
    if total_chunks > 1:
        print(f"Found {len(filings_to_process)} total unprocessed filings.")
        num_reports = len(filings_to_process)
        chunk_size = (num_reports + total_chunks - 1) // total_chunks
        start_index = chunk_index * chunk_size
        end_index = start_index + chunk_size
        filings_to_process = filings_to_process[start_index:end_index]
        print(
            f"   -> This machine's workload: {len(filings_to_process)} filings (index {start_index} to {end_index})."
        )

    if not filings_to_process:
        print("✅ No new filings for this chunk to process. Exiting.")
        sys.exit(0)

    total_processed = 0
    total_positive = 0
    start_time = time.time()

    # 4. Process filings in parallel with intermediate checkpoints
    try:
        with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
            future_to_filing = {
                executor.submit(process_filing, filing): filing
                for filing in filings_to_process
            }

            progress_bar = tqdm(
                as_completed(future_to_filing),
                total=len(filings_to_process),
                desc="Processing Filings",
            )

            for future in progress_bar:
                try:
                    result = future.result()
                    if result:
                        all_chunk_results.append(result)
                        total_processed += 1
                        if result.get("found_notional"):
                            total_positive += 1

                        # Save intermediate checkpoint every N filings
                        if len(all_chunk_results) % SAVE_INTERVAL_FILINGS == 0:
                            saved_count = save_chunk_to_parquet(
                                all_chunk_results, output_parquet_file
                            )
                            print(
                                f"\n💾 Checkpoint saved: {saved_count} total results to {output_parquet_file}"
                            )

                except Exception as e:
                    filing_url = future_to_filing[future][0]
                    print(f"❌ Error processing filing {filing_url}: {e}")

    except KeyboardInterrupt:
        print("\n🛑 Process interrupted by user. Saving pending results...")

    finally:
        # 5. Final save for any remaining results
        if all_chunk_results:
            print(f"\n💾 Saving final results for this chunk...")
            saved_count = save_chunk_to_parquet(all_chunk_results, output_parquet_file)
            print(f"   -> Saved {saved_count} total records to {output_parquet_file}.")

        # 6. Optional: Backup to Google Drive
        if IS_COLAB and Path(output_parquet_file).exists():
            print(f"\n☁️ Backing up {output_parquet_file} to Google Drive...")
            import subprocess

            drive_dest = f"{DRIVE_PATH}/{output_parquet_file}"
            subprocess.run(
                f"cp -f {output_parquet_file} {drive_dest}.tmp && mv -f {drive_dest}.tmp {drive_dest}",
                shell=True,
            )
            print("  -> Backup complete.")

        # 7. Print summary
        total_time = time.time() - start_time
        print("\n" + "=" * 80)
        print("✅ CLASSIFICATION COMPLETE")
        print("=" * 80)
        print(f"Total filings processed in this run: {total_processed}")
        print(f"Filings with positive H3_Notional entailment: {total_positive}")
        print(f"Total time: {time.strftime('%H:%M:%S', time.gmtime(total_time))}")
        print(f"💾 Results for this chunk saved to '{output_parquet_file}'")
        if total_chunks > 1:
            print(f"ℹ️  Remember to merge all chunk files when processing is complete.")
        print("\n✨ Done!")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Run the database-driven classification client in standalone or chunked mode."
    )
    parser.add_argument(
        "--total-chunks",
        type=int,
        default=1,
        help="Total number of chunks to split the workload into.",
    )
    parser.add_argument(
        "--chunk-index",
        type=int,
        default=0,
        help="The 0-based index of the chunk this instance should process.",
    )
    args = parser.parse_args()

    if not (0 <= args.chunk_index < args.total_chunks):
        print("❌ Error: --chunk-index must be between 0 and --total-chunks-1.")
        sys.exit(1)

    run_classification(args.total_chunks, args.chunk_index)
