import argparse
import os
import subprocess
import sys
import psutil
import multiprocessing as mp
import platform
import time
import json
import shutil

# =============================================================================
# CONFIGURATION
# =============================================================================

MODEL_PATH = "DerivedFunction/Qwen3-1.7B-derivatives-classifier"
MODEL_SIZE_GB = 3.5  # Approximate size of the loaded model (3-4GB)
ESTIMATED_OVERHEAD_GB = 1.0  # Memory overhead per process

# Server ports
NGINX_PORT = 5000
BASE_GPU_SERVER_PORT = 5001

# File paths
PID_FILE = "server.pid"
NGINX_CONF_FILE = "nginx.conf"
SERVER_SCRIPT = "server:app"
CACHE_FILE = ".server_cache.json"
CONFIG_FILE = ".server_config.json"  # NEW: Config file for classify.py

# Gunicorn settings
GUNICORN_TIMEOUT = 120

# =============================================================================
# CONFIGURATION FILE MANAGEMENT
# =============================================================================


def save_config(num_processes, num_threads_per_process, gpu_ram_gb):
    """
    Save server configuration to a JSON file that classify.py can read.
    This allows classify.py to know how many threads to use.
    """
    config = {
        "timestamp": time.time(),
        "num_processes": num_processes,
        "num_threads_per_process": num_threads_per_process,
        "gpu_ram_gb": gpu_ram_gb,
        "notes": "This file is auto-generated by run_server.py. You can manually edit num_threads_per_process.",
    }
    try:
        with open(CONFIG_FILE, "w") as f:
            json.dump(config, f, indent=2)
        print(f"✅ Configuration saved to '{CONFIG_FILE}'")
    except IOError as e:
        print(f"⚠️  Could not write config file: {e}")


def load_config():
    """Load configuration from file."""
    if not os.path.exists(CONFIG_FILE):
        return None
    try:
        with open(CONFIG_FILE, "r") as f:
            return json.load(f)
    except (json.JSONDecodeError, IOError):
        return None


# =============================================================================
# CACHING FUNCTIONS
# =============================================================================


def load_cache():
    """Load cached system info if it exists and is recent (< 24 hours old)."""
    if not os.path.exists(CACHE_FILE):
        return None

    try:
        with open(CACHE_FILE, "r") as f:
            cache = json.load(f)

        cache_age = time.time() - cache.get("timestamp", 0)
        if cache_age < 60 * 60 * 24:
            return cache
    except (json.JSONDecodeError, IOError):
        pass

    return None


def save_cache(model_available, gpu_ram_gb):
    """Save system info to cache file."""
    cache = {
        "timestamp": time.time(),
        "model_available": model_available,
        "gpu_ram_gb": gpu_ram_gb,
    }
    try:
        with open(CACHE_FILE, "w") as f:
            json.dump(cache, f)
    except IOError as e:
        print(f"⚠️  Could not write cache file: {e}")


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================


def pre_download_model():
    """Downloads the model before starting servers."""
    cache = load_cache()
    if cache and cache.get("model_available"):
        print("✅ Model is available (cached).")
        return True

    print("🔍 Checking for model...")
    try:
        from transformers import AutoTokenizer

        AutoTokenizer.from_pretrained(MODEL_PATH)
        print("✅ Model is available locally.")
        return True
    except ImportError:
        print("⚠️  Could not import 'transformers'.")
        return False
    except Exception as e:
        print(f"❌ Model pre-download error: {e}")
        return False


def check_nginx():
    """Checks if nginx is installed."""
    if shutil.which("nginx") is not None:
        print("✅ Nginx is available.")
        return True

    print("❌ ERROR: 'nginx' command not found.")
    if platform.system() == "Linux":
        try:
            distro_id = platform.freedesktop_os_release().get("ID")
            if distro_id in ["ubuntu", "debian"]:
                install_prompt = (
                    input(
                        "   Would you like to install it? (sudo apt install nginx) [y/N]: "
                    )
                    .lower()
                    .strip()
                )
                if install_prompt == "y":
                    print(
                        "   -> Running 'sudo apt update && sudo apt install -y nginx'..."
                    )
                    try:
                        subprocess.check_call("sudo apt update".split())
                        subprocess.check_call("sudo apt install -y nginx".split())
                        if shutil.which("nginx"):
                            print("   ✅ Nginx installed successfully.")
                            return True
                    except (subprocess.CalledProcessError, FileNotFoundError) as e:
                        print(f"   ❌ Installation failed: {e}")
                        return False
        except (AttributeError, FileNotFoundError):
            pass

    print("   Please install Nginx manually.")
    return False


def check_gunicorn():
    """Checks if gunicorn is installed."""
    if shutil.which("gunicorn") is not None:
        return True

    print("\n⚠️  'gunicorn' command not found.")
    install_prompt = (
        input("   Install it now? (pip install gunicorn) [y/N]: ").lower().strip()
    )
    if install_prompt == "y":
        subprocess.check_call([sys.executable, "-m", "pip", "install", "gunicorn"])
        return shutil.which("gunicorn") is not None
    return False


def check_uvicorn():
    """Ensure uvicorn (ASGI server) is available for gunicorn worker class.

    Gunicorn with FastAPI must use an ASGI worker such as uvicorn.workers.UvicornWorker.
    This function checks that uvicorn is importable (or installed as a CLI) and
    offers to install it if missing.
    """
    # Check for uvicorn CLI first
    if shutil.which("uvicorn") is not None:
        return True

    # If CLI not found, try importing the package
    try:
        import uvicorn  # type: ignore

        return True
    except Exception:
        pass

    print("\n⚠️  'uvicorn' package not found. Gunicorn will need uvicorn to run ASGI apps.")
    install_prompt = (
        input("   Install it now? (pip install uvicorn[standard]) [y/N]: ").lower().strip()
    )
    if install_prompt == "y":
        subprocess.check_call([sys.executable, "-m", "pip", "install", "uvicorn[standard]"])
        try:
            import uvicorn  # type: ignore
            return True
        except Exception:
            return False

    return False

def check_waitress():
    """Checks if waitress is installed, which is needed for Windows."""
    if shutil.which("waitress-serve") is not None:
        return True

    print("⚠️  'waitress-serve' command not found.")
    install_prompt = (
        input("   It's needed for Windows support. Install it now? (pip install waitress) [y/N]: ")
        .lower()
        .strip()
    )
    if install_prompt == "y":
        subprocess.check_call([sys.executable, "-m", "pip", "install", "waitress"])
        return shutil.which("waitress-serve") is not None
    return False

def is_windows():
    """Check if the operating system is Windows."""
    return platform.system() == "Windows"


def get_system_resources():
    """Detects system CPU cores and RAM."""
    cpu_cores = mp.cpu_count()
    ram_gb = psutil.virtual_memory().total / (1024**3)
    return cpu_cores, ram_gb


def get_gpu_ram():
    """Detects GPU RAM using torch."""
    cache = load_cache()
    if cache and "gpu_ram_gb" in cache:
        gpu_ram = cache["gpu_ram_gb"]
        if gpu_ram > 0:
            print(f"✅ GPU RAM: {gpu_ram:.2f} GB (cached).")
        else:
            print("   - No GPU detected (cached).")
        return gpu_ram

    print("🔎 Detecting GPU RAM...")
    gpu_ram = 0
    try:
        import torch

        if torch.cuda.is_available():
            gpu_name = torch.cuda.get_device_name(0)
            gpu_ram = torch.cuda.get_device_properties(0).total_memory / (1024**3)
            print(f"✅ GPU Detected: {gpu_name} with {gpu_ram:.2f} GB RAM.")
        else:
            print("   - No CUDA-enabled GPU found.")
    except ImportError:
        print("⚠️  'torch' is not installed.")
    except Exception as e:
        print(f"⚠️  GPU detection error: {e}")

    return gpu_ram


def calculate_num_processes(gpu_ram_gb):
    """
    Calculate how many model processes can fit in GPU memory.
    """
    if gpu_ram_gb <= 0:
        print("   - No GPU available.")
        return 1

    available_for_models = gpu_ram_gb - ESTIMATED_OVERHEAD_GB
    num_processes = max(1, int(available_for_models / MODEL_SIZE_GB))

    # Cap at a reasonable number
    num_processes = min(num_processes, 8)

    print(f"   - Available GPU memory for models: {available_for_models:.2f} GB")
    print(f"   - Model size: ~{MODEL_SIZE_GB} GB")
    print(f"   - Calculated processes: {num_processes}")

    return num_processes


def calculate_threads_per_process(cpu_cores, num_processes):
    """
    Set threads to 1 per process for stability.
    Each process handles requests sequentially to avoid threading contention.
    Parallelism comes from having multiple processes, not multiple threads.
    """
    return 1


def generate_nginx_config(num_processes, base_port):
    """
    Generates the nginx.conf file with all processes as upstreams.
    """
    log_dir = os.path.abspath("logs")
    os.makedirs(log_dir, exist_ok=True)
    access_log_path = os.path.join(log_dir, "nginx_access.log").replace(os.sep, "/")
    error_log_path = os.path.join(log_dir, "nginx_error.log").replace(os.sep, "/")

    # Create upstream entries for each process
    upstream_servers = "\n        ".join(
        [f"server 127.0.0.1:{base_port + i};" for i in range(num_processes)]
    )

    config = f"""
worker_processes auto;
pid {os.path.abspath(PID_FILE).replace(os.sep, '/')};

events {{
    worker_connections 1024;
}}

http {{
    access_log {access_log_path};
    error_log {error_log_path};

    upstream model_servers {{
        {upstream_servers}
    }}

    server {{
        listen {NGINX_PORT};
        server_name localhost;

        location / {{
            proxy_pass http://model_servers;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504 non_idempotent;

            proxy_connect_timeout {GUNICORN_TIMEOUT};
            proxy_send_timeout {GUNICORN_TIMEOUT};
            proxy_read_timeout {GUNICORN_TIMEOUT};
            proxy_buffering off;
        }}
    }}
}}
"""
    with open(NGINX_CONF_FILE, "w") as f:
        f.write(config)

    print(f"✅ Nginx config generated: {num_processes} backend processes")


def interactive_config_editor(num_processes, threads_per_process, gpu_ram_gb):
    """Allow user to adjust the calculated configuration."""
    while True:
        print("\n" + "=" * 70)
        print("🤖 Auto-Detected Server Configuration:")
        print(f"   [1] Number of Processes:  {num_processes}")
        print(f"   [2] Threads per Process:  {threads_per_process}")
        print(f"   GPU Memory Available:      {gpu_ram_gb:.2f} GB")
        print("=" * 70)

        prompt = "Accept this configuration and start servers? [Y/n] or enter a number to edit: "
        choice = input(prompt).lower().strip()

        if choice in ["y", "yes", ""]:
            break

        if choice == "n":
            continue

        try:
            choice_num = int(choice)
            if choice_num == 1:
                num_processes = int(
                    input(
                        f"   Enter new number of processes (current: {num_processes}): "
                    )
                )
                num_processes = max(1, min(num_processes, 8))
            elif choice_num == 2:
                threads_per_process = int(
                    input(
                        f"   Enter new threads per process (current: {threads_per_process}): "
                    )
                )
                threads_per_process = max(1, min(threads_per_process, 16))
            else:
                print(f"   Invalid number. Please enter 1 or 2.")
        except ValueError:
            print(f"   Invalid input. Please enter 'y', 'n', or a number.")

    return num_processes, threads_per_process


def start_servers():
    """Starts the Gunicorn and Nginx servers."""
    if is_windows():
        print(
            "ℹ️  Windows detected. Using 'waitress' server instead of Gunicorn/Nginx."
        )
        if not check_waitress():
            print("❌ Cannot start server on Windows without 'waitress'.")
            return

        # Get system info for caching and display
        model_available = pre_download_model()
        gpu_ram_gb = get_gpu_ram()
        save_cache(model_available, gpu_ram_gb)

        # On Windows, we run a single server process.
        # The server.py script itself will detect the GPU and use it if available.
        print(f"🚀 Starting server with waitress on http://127.0.0.1:{NGINX_PORT}")
        print("   The server will automatically use the GPU if it is available.")
        print("   To stop the server, press Ctrl+C in this window.")

        # Command to run the waitress server
        waitress_cmd = (
            f"waitress-serve --host 127.0.0.1 --port {NGINX_PORT} {SERVER_SCRIPT}"
        )

        try:
            # Run the server in the foreground
            subprocess.run(waitress_cmd.split())
        except KeyboardInterrupt:
            print("\n✅ Server stopped by user.")
        except Exception as e:
            print(f"❌ An error occurred while running the waitress server: {e}")
        return

    # Check dependencies
    if not check_nginx():
        return
    if not check_gunicorn():
        return
    # Ensure uvicorn is available so gunicorn can use UvicornWorker for ASGI
    if not check_uvicorn():
        return

    # Get system info
    model_available = pre_download_model()
    cpu_cores, ram_gb = get_system_resources()
    gpu_ram_gb = get_gpu_ram()

    save_cache(model_available, gpu_ram_gb)

    # Calculate configuration
    num_processes = calculate_num_processes(gpu_ram_gb)
    threads_per_process = calculate_threads_per_process(cpu_cores, num_processes)

    # Interactive configuration
    num_processes, threads_per_process = interactive_config_editor(
        num_processes, threads_per_process, gpu_ram_gb
    )

    # Save config for classify.py to read
    save_config(num_processes, threads_per_process, gpu_ram_gb)

    print("\n" + "=" * 70)
    print("🚀 Starting Servers:")
    print(
        f"   System: {cpu_cores} CPU cores, {ram_gb:.1f} GB RAM, {gpu_ram_gb:.1f} GB GPU"
    )
    print(
        f"   Spawning {num_processes} model processes with {threads_per_process} threads each"
    )
    print("=" * 70 + "\n")

    # Generate Nginx config
    generate_nginx_config(num_processes, BASE_GPU_SERVER_PORT)

    # Spawn model processes
    processes = []
    for i in range(num_processes):
        port = BASE_GPU_SERVER_PORT + i
        # Use UvicornWorker so FastAPI (ASGI) is served correctly under gunicorn
        cmd = (
            f"gunicorn --workers 1 --threads {threads_per_process} --timeout {GUNICORN_TIMEOUT} -k uvicorn.workers.UvicornWorker "
            f"--bind 127.0.0.1:{port} --backlog 2048 {SERVER_SCRIPT}"
        )
        proc = subprocess.Popen(cmd.split())
        processes.append(proc)
        print(f"🚀 Launched model process {i+1}/{num_processes} on port {port}")

    # Start Nginx
    nginx_cmd = f"nginx -c {os.path.abspath(NGINX_CONF_FILE)}"
    subprocess.Popen(nginx_cmd.split())
    print(f"🚀 Launched Nginx load balancer on port {NGINX_PORT}\n")

    print(f"✅ All services started at http://127.0.0.1:{NGINX_PORT}")


def stop_servers():
    """Stops all servers."""
    print("🛑 Stopping all services...")

    if os.path.exists(PID_FILE):
        nginx_stop_cmd = f"nginx -s stop -c {os.path.abspath(NGINX_CONF_FILE)}"
        subprocess.run(nginx_stop_cmd.split(), check=False)
        print("   - Nginx stopped.")
        try:
            os.remove(PID_FILE)
        except OSError:
            pass

    try:
        subprocess.run(f"pkill -f 'gunicorn.*{SERVER_SCRIPT}'", shell=True, check=False)
        print("   - Gunicorn processes stopped.")
    except Exception as e:
        print(f"   - Could not stop Gunicorn: {e}")

    print("✅ All services stopped.")


# =============================================================================
# MAIN CLI
# =============================================================================

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Manage FastAPI servers with automatic model-based process spawning.",
        formatter_class=argparse.RawTextHelpFormatter,
    )
    parser.add_argument(
        "action",
        nargs="?",
        default=None,
        choices=["start", "stop", "restart", "status", "clear-cache"],
        help="""
start       - Start the FastAPI and Nginx servers.
stop        - Stop all running servers.
restart     - Stop and then start all servers.
status      - Check if the servers are running.
clear-cache - Clear the cached system information.
""",
    )

    args = parser.parse_args()
    action = args.action

    if action is None:
        if os.path.exists(PID_FILE):
            print("ℹ️ Servers appear to be running. Stopping them now.")
            stop_servers()
        else:
            print("ℹ️ Servers appear to be stopped. Starting them now.")
            start_servers()
    elif action == "start":
        start_servers()
    elif action == "stop":
        stop_servers()
    elif action == "restart":
        stop_servers()
        print("\nRestarting in 3 seconds...")
        time.sleep(3)
        start_servers()
    elif action == "status":
        if os.path.exists(PID_FILE):
            print("✅ Servers appear to be RUNNING.")
        else:
            print("❌ Servers appear to be STOPPED.")
    elif action == "clear-cache":
        if os.path.exists(CACHE_FILE):
            os.remove(CACHE_FILE)
            print("✅ Cache cleared.")
        if os.path.exists(CONFIG_FILE):
            os.remove(CONFIG_FILE)
            print("✅ Config cleared.")
        else:
            print("ℹ️ No cache/config files found.")
