from flask import Flask, request, jsonify, Response
from flask_cors import CORS
import torch
import os
import json
from unsloth import FastLanguageModel
from transformers import TextIteratorStreamer
from threading import Thread
import multiprocessing as mp

app = Flask(__name__)
CORS(app)  # Enable Cross-Origin Resource Sharing for the entire app

# --- CONFIGURATION ---
MODEL_PATH = "DerivedFunction/derivatives-classifier-4B"  # Your new generative model
MAX_SEQ_LENGTH = 4096

# --- LOAD MODEL WITH UNSLOTH ---
print(f"Loading model: {MODEL_PATH}...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=MODEL_PATH,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,  # Auto-detect dtype
    load_in_4bit=True,
)
FastLanguageModel.for_inference(model)  # Optimize for faster inference
print("✅ Model loaded successfully.")

# Check for an environment variable to force CPU, otherwise default to GPU if available
DEVICE_TYPE = os.environ.get("DEVICE_TYPE", "gpu").lower()
if DEVICE_TYPE == "cpu":
    device = torch.device("cpu")
else:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Note: Unsloth handles model placement, so model.to(device) is not explicitly needed here.


def generate_response(prompt: str):
    """
    Generates a response from the model for a single prompt.
    """
    print(f"DEBUG: Received prompt for generation: {prompt[:100]}...") # Print first 100 chars
    # Format the prompt using Qwen's chat template
    formatted_prompt = f"<|im_start|>user\n{prompt}<|im_end|>\n<|im_start|>assistant\n"
    print(f"DEBUG: Formatted prompt: {formatted_prompt[:200]}...") # Print first 200 chars of formatted prompt
    inputs = tokenizer([formatted_prompt], return_tensors="pt").to(device)

    with torch.no_grad():
        print("DEBUG: Generating model output...")
        outputs = model.generate(
            **inputs,
            max_new_tokens=1024,  # Adjust as needed for your expected output size
            use_cache=True,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
            do_sample=False, # For deterministic output during debugging
        )

    # Decode and extract the assistant's response
    response_text = tokenizer.batch_decode(outputs, skip_special_tokens=False)[0]

    try:
        # Extract only the content generated by the assistant
        print(f"DEBUG: Raw model response_text: {response_text}")
        assistant_part = response_text.split("<|im_start|>assistant")[-1]
        # Clean up special tokens
        cleaned_response = assistant_part.replace("<|im_end|>", "").strip()
        # The model should output a JSON object.
        print(f"DEBUG: Cleaned assistant response: {cleaned_response}")
        return json.loads(cleaned_response)
    except (json.JSONDecodeError, IndexError) as e:
        print(f"ERROR: Failed to parse model output as JSON: {e}")
        return {"error": "Failed to parse model output as JSON", "raw_output": response_text, "exception": str(e)}

def generate_stream(prompt: str):
    """
    Generates a response from the model as a stream of tokens.
    """
    streamer = TextIteratorStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)

    # Format the prompt using Qwen's chat template
    formatted_prompt = f"<|im_start|>user\n{prompt}<|im_end|>\n<|im_start|>assistant\n"
    inputs = tokenizer([formatted_prompt], return_tensors="pt").to(device)

    generation_kwargs = dict(
        inputs,
        streamer=streamer,
        max_new_tokens=2048,
        use_cache=True,
        pad_token_id=tokenizer.eos_token_id,
        eos_token_id=tokenizer.eos_token_id,
        do_sample=False,
    )

    # Run the generation in a separate thread to avoid blocking
    thread = Thread(target=model.generate, kwargs=generation_kwargs)
    thread.start()

    # Yield the generated tokens as they become available
    for new_text in streamer:
        yield new_text

@app.route("/generate-stream", methods=["POST"])
def generate_stream_endpoint():
    data = request.json
    prompt = data.get("prompt", "")
    return Response(generate_stream(prompt), mimetype='text/plain')


@app.route("/generate", methods=["POST"])
def generate_endpoint():
    data = request.json
    if not data or "prompt" not in data or not isinstance(data["prompt"], str):
        return jsonify({"error": "Missing or invalid 'prompt' field; must be a string"}), 400

    prompt = data["prompt"]
    prediction = generate_response(prompt)
    print("DEBUG: Sending prediction back to client.")
    return jsonify({"prediction": prediction})


@app.route("/info", methods=["GET"])
def info_endpoint():
    """Provides information about the server's GPU, if available."""
    info = {"device_in_use": str(device)}
    if torch.cuda.is_available():
        gpu_name = torch.cuda.get_device_name(0)
        total_memory_gb = torch.cuda.get_device_properties(0).total_memory / (1024**3)
        info.update({
            "gpu_available": True,
            "gpu_name": gpu_name,
            "total_ram_gb": round(total_memory_gb, 2),
        })
    else:
        info.update({
            "gpu_available": False,
            "message": "No CUDA-enabled GPU found.",
            "cpu_cores": mp.cpu_count(),
        })
    return jsonify(info)


if __name__ == "__main__":
    # For production, use a proper WSGI server like Gunicorn or Waitress
    app.run(host="0.0.0.0", port=5000)
