from flask import Flask, request, jsonify
import torch
import os
import json
from unsloth import FastLanguageModel
import multiprocessing as mp

app = Flask(__name__)

# --- CONFIGURATION ---
MODEL_PATH = "DerivedFunction/derivatives-classifier-4B"  # Your new generative model
MAX_SEQ_LENGTH = 2048

# --- LOAD MODEL WITH UNSLOTH ---
print(f"Loading model: {MODEL_PATH}...")
model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=MODEL_PATH,
    max_seq_length=MAX_SEQ_LENGTH,
    dtype=None,  # Auto-detect dtype
    load_in_4bit=True,
)
FastLanguageModel.for_inference(model)  # Optimize for faster inference
print("✅ Model loaded successfully.")

# Check for an environment variable to force CPU, otherwise default to GPU if available
DEVICE_TYPE = os.environ.get("DEVICE_TYPE", "gpu").lower()
if DEVICE_TYPE == "cpu":
    device = torch.device("cpu")
else:
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Note: Unsloth handles model placement, so model.to(device) is not explicitly needed here.


def generate_response(prompt: str) -> dict:
    """
    Generates a response from the model for a single prompt.
    """
    # Format the prompt using Qwen's chat template
    formatted_prompt = f"<|im_start|>user\n{prompt}<|im_end|>\n<|im_start|>assistant\n"
    inputs = tokenizer([formatted_prompt], return_tensors="pt").to(device)

    with torch.no_grad():
        outputs = model.generate(
            **inputs,
            max_new_tokens=1024,  # Adjust as needed for your expected output size
            use_cache=True,
            pad_token_id=tokenizer.eos_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )

    # Decode and extract the assistant's response
    response_text = tokenizer.batch_decode(outputs, skip_special_tokens=False)[0]

    try:
        # Extract only the content generated by the assistant
        assistant_part = response_text.split("<|im_start|>assistant")[-1]
        # Clean up special tokens
        cleaned_response = assistant_part.replace("<|im_end|>", "").strip()
        # The model should output a JSON object.
        return json.loads(cleaned_response)
    except (json.JSONDecodeError, IndexError) as e:
        return {"error": "Failed to parse model output as JSON", "raw_output": response_text}


@app.route("/generate", methods=["POST"])
def generate_endpoint():
    data = request.json
    if not data or "prompt" not in data or not isinstance(data["prompt"], str):
        return jsonify({"error": "Missing or invalid 'prompt' field; must be a string"}), 400

    prompt = data["prompt"]
    prediction = generate_response(prompt)
    return jsonify({"prediction": prediction})


@app.route("/info", methods=["GET"])
def info_endpoint():
    """Provides information about the server's GPU, if available."""
    info = {"device_in_use": str(device)}
    if torch.cuda.is_available():
        gpu_name = torch.cuda.get_device_name(0)
        total_memory_gb = torch.cuda.get_device_properties(0).total_memory / (1024**3)
        info.update({
            "gpu_available": True,
            "gpu_name": gpu_name,
            "total_ram_gb": round(total_memory_gb, 2),
        })
    else:
        info.update({
            "gpu_available": False,
            "message": "No CUDA-enabled GPU found.",
            "cpu_cores": mp.cpu_count(),
        })
    return jsonify(info)


if __name__ == "__main__":
    # For production, use a proper WSGI server like Gunicorn or Waitress
    app.run(host="0.0.0.0", port=5000)
