import pandas as pd
import requests
import json
from pathlib import Path
from tqdm import tqdm

# =============================================================================
# CONFIGURATION
# =============================================================================

# --- INPUT ---
# Create this Parquet file and add your test prompts in a column named 'prompt'.
INPUT_PARQUET_PATH = "test_prompts.parquet"

# --- OUTPUT ---
# The script will create this file with the model's generated JSON. It's saved as Parquet
# to avoid any potential character limits in the output as well.
OUTPUT_PARQUET_PATH = "test_results_generative.parquet"

# --- SERVER ---
# Make sure your new server (server2.py) is running at this address.
SERVER_URL = "http://127.0.0.1:5000/generate"

# =============================================================================
# SERVER COMMUNICATION
# =============================================================================

def get_generation_from_server(prompt: str) -> dict:
    """
    Sends a single prompt to the model server and returns the generated JSON.

    Args:
        prompt (str): The prompt string to send to the model.

    Returns:
        dict: The JSON dictionary generated by the model.
    """
    headers = {"Content-Type": "application/json"}
    payload = {"prompt": prompt}

    try:
        response = requests.post(SERVER_URL, headers=headers, data=json.dumps(payload), timeout=300)
        response.raise_for_status()  # Raise an exception for bad status codes
        return response.json().get("prediction", {})
    except requests.exceptions.RequestException as e:
        print(f"\nError communicating with the server: {e}")
        return {"error": "network_error", "details": str(e)}

# =============================================================================
# MAIN EXECUTION
# =============================================================================

def main():
    """Main function to run the generative model test script."""
    input_path = Path(INPUT_PARQUET_PATH)
    training_data_path = Path("training_data.parquet")

    if not input_path.exists():
        print(f"Input file not found at '{INPUT_PARQUET_PATH}'.")

        if training_data_path.exists():
            print(f"Attempting to create a sample from '{training_data_path}'...")
            try:
                training_df = pd.read_parquet(training_data_path)
                if "prompt" in training_df.columns and not training_df.empty:
                    sample_size = min(5, len(training_df))
                    sample_df = training_df.sample(n=sample_size)[["prompt"]]
                    sample_df.to_parquet(input_path, index=False)
                    print(f"✅ A sample file with {sample_size} prompts from your training data has been created at '{input_path}'.")
                    print("   You can now run the script again to test with these prompts.")
                else:
                    raise ValueError("Training data is empty or missing 'prompt' column.")
            except Exception as e:
                print(f"   -> Could not use training data ({e}). Creating a generic sample file instead.")
                pd.DataFrame({'prompt': ['Analyze the following text...']}).to_parquet(input_path, index=False)
                print(f"   A generic sample file has been created for you at '{input_path}'. Please edit it and run again.")
        else:
            print(f"'{training_data_path}' not found. Creating a generic sample file.")
            pd.DataFrame({'prompt': ['Analyze the following text...']}).to_parquet(input_path, index=False)
            print(f"A sample file has been created for you at '{input_path}'. Please edit it and run again.")
        return

    print(f"Reading prompts from '{input_path}'...")
    df = pd.read_parquet(input_path)

    if "prompt" not in df.columns:
        print("Error: The input Excel file must contain a column named 'prompt'.")
        return

    prompts_to_run = df["prompt"].dropna().tolist()
    if not prompts_to_run:
        print("No prompts found in the 'prompt' column.")
        return

    predictions = [get_generation_from_server(p) for p in tqdm(prompts_to_run, desc="Generating responses")]

    df["model_generation"] = [json.dumps(p, indent=2) for p in predictions]
    df.to_parquet(OUTPUT_PARQUET_PATH, index=False)
    print(f"\n✅ Success! Generations saved to '{OUTPUT_PARQUET_PATH}'.")

if __name__ == "__main__":
    main()
