# =============================================================================
# DATABASE-DRIVEN SENTENCE CLASSIFICATION CLIENT
# =============================================================================
# This script reads pre-filtered and categorized sentences from the
# 'clean_web_data.db' (generated by filter_database.py) and sends them
# to the classification server for NLI analysis.
#
# It implements:
# 1. Multi-stage hypothesis classification (Policy, Notional, Position, PnL)
# 2. Early-exit strategy for maximum efficiency
# 3. Robust resumable processing with intermediate checkpoints
# 4. Mini-chunk processing with periodic saves and stats
# 5. Multi-machine support via chunking
# 6. Google Drive backups
# 7. Category-specific results with (url, category) composite key
# 8. Array-based findings tracking (stores all matching sentence indices)
# =============================================================================

import requests
import sqlite3
import json
import sys
import argparse
import pandas as pd
import time
import subprocess
from tqdm import tqdm
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import List, Dict, Optional, Tuple, Any
from pathlib import Path
from collections import Counter

# =============================================================================
# CONFIGURATION
# =============================================================================

# Database path for the clean, filtered data
DB_PATH = "clean_web_data.db"

# API endpoint of your classification server
SERVER_BASE_URL = "http://127.0.0.1:5000"
CLASSIFY_ENDPOINT = f"{SERVER_BASE_URL}/classify"
INFO_ENDPOINT = f"{SERVER_BASE_URL}/info"

# Results configuration
RESULTS_TABLE = "classification_results"
RESULTS_PARQUET_TEMPLATE = "classification_results_chunk_{}.parquet"

# Processing configuration
SAVE_INTERVAL_FILINGS = 500  # Save checkpoint every N filings
MAX_WORKERS = 2
BATCH_SIZE = 32

# Google Drive configuration
DRIVE_PATH = "./drive/MyDrive/db"
DRIVE_SAVE_INTERVAL_SECONDS = 10 * 60  # 10 minutes
DRIVE_SAVE_INTERVAL_RESULTS = 2000  # Save after N results
IS_COLAB = Path(DRIVE_PATH).exists()

if IS_COLAB:
    print("Running in Google Colab environment.")

# Map derivative types from the DB to the 'term' for the model
DERIVATIVE_TYPE_TO_TERM_MAP = {
    "ir_matches": "interest rate derivative",
    "fx_matches": "foreign exchange derivative",
    "cp_matches": "commodity derivative",
    "eq_matches": "equity derivative",
}

# Category short names
CATEGORY_MAPPING = {
    "ir_matches": "ir",
    "fx_matches": "fx",
    "cp_matches": "cp",
    "eq_matches": "eq",
}

# This needs to be in sync with the server's STAGE_HYPOTHESES_MAP
STAGE_HYPOTHESES_MAP = {
    "policy": ["H1_Policy"],
    "notional": ["H3_Notional"],
    "position": ["H2_Existence", "H4_PnL_Impact"],
}

# =============================================================================
# HELPER FUNCTIONS
# =============================================================================


def format_time(seconds):
    """Format seconds into human-readable time string."""
    hours, remainder = divmod(seconds, 3600)
    minutes, seconds = divmod(remainder, 60)
    if hours > 0:
        return f"{int(hours)}h {int(minutes)}m {int(seconds)}s"
    elif minutes > 0:
        return f"{int(minutes)}m {int(seconds)}s"
    else:
        return f"{int(seconds)}s"


def prepare_results_for_parquet(results: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Normalize results to a flat, consistent structure for Parquet storage.
    Ensures all results have the same schema, preventing write errors.
    Each result now includes:
    - url, cik, year, category
    - found_policy, found_existence, found_notional, found_pnl (JSON arrays)
    - status, duration_s, error_message
    """
    normalized = []
    found_types = ["policy", "existence", "notional", "pnl"]

    for r in results:
        record = {
            "url": r.get("url"),
            "cik": r.get("cik"),
            "year": r.get("year"),
            "category": r.get("category"),
            "status": str(r.get("status", "unknown")),
            "duration_s": float(r.get("duration_s", 0.0)),
            "error_message": (
                str(r.get("error_message")) if r.get("error_message") else None
            ),
        }
        # Add the granular 'found' columns (now storing arrays as JSON strings)
        for f_type in found_types:
            col_name = f"found_{f_type}"
            indices_array = r.get(col_name, [])
            # Store as JSON string in parquet
            record[col_name] = json.dumps(indices_array)
        normalized.append(record)
    return normalized


def save_chunk_to_parquet(
    all_results: List[Dict[str, Any]], output_parquet_path: str
) -> int:
    """
    Saves results to a Parquet file with proper schema normalization.
    Returns the number of rows saved.
    """
    if not all_results:
        return 0

    try:
        normalized_results = prepare_results_for_parquet(all_results)
        df = pd.DataFrame(normalized_results)
        df.to_parquet(output_parquet_path, index=False)
        return len(df)
    except Exception as e:
        print(f"    ❌ Error saving to Parquet file {output_parquet_path}: {e}")
        return 0


def backup_to_drive(output_parquet_file: str):
    """
    Backs up the parquet file to Google Drive if running in Colab.
    """
    if not IS_COLAB:
        return

    try:
        drive_dest = f"{DRIVE_PATH}/{output_parquet_file}"
        subprocess.run(
            f"cp -f {output_parquet_file} {drive_dest}.tmp && mv -f {drive_dest}.tmp {drive_dest}",
            shell=True,
            check=True,
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    except Exception as e:
        print(f"    ⚠️ Failed to backup to Drive: {e}")


def get_already_processed_in_parquet(
    output_parquet_file: str,
) -> Tuple[set, List[Dict]]:
    """
    Check if a parquet checkpoint exists and load already-processed (url, category) pairs.
    Returns: (set of (url, category) tuples, list of existing results)
    """
    if not Path(output_parquet_file).exists():
        return set(), []

    try:
        df = pd.read_parquet(output_parquet_file)
        # Create composite key of (url, category)
        processed_pairs = set(zip(df["url"].tolist(), df["category"].tolist()))

        # Parse JSON arrays back to lists
        existing_results = df.to_dict("records")
        for result in existing_results:
            for f_type in ["policy", "existence", "notional", "pnl"]:
                col_name = f"found_{f_type}"
                if col_name in result and isinstance(result[col_name], str):
                    result[col_name] = json.loads(result[col_name])

        return processed_pairs, existing_results
    except Exception as e:
        print(f"    ⚠️ Could not read parquet checkpoint: {e}")
        return set(), []


def print_mini_chunk_stats(mini_chunk_results: List[Dict[str, Any]]):
    """
    Print statistics for the current mini-chunk.
    """
    if not mini_chunk_results:
        return

    statuses = Counter(r.get("status") for r in mini_chunk_results)

    # Count findings (any found_* array with len > 0 means it was found)
    found_types = ["policy", "existence", "notional", "pnl"]
    findings_count = {f_type: 0 for f_type in found_types}
    total_matches = {f_type: 0 for f_type in found_types}

    for r in mini_chunk_results:
        for f_type in found_types:
            col_name = f"found_{f_type}"
            indices_array = r.get(col_name, [])
            if len(indices_array) > 0:
                findings_count[f_type] += 1
                total_matches[f_type] += len(indices_array)

    avg_duration = sum(r.get("duration_s", 0) for r in mini_chunk_results) / (
        len(mini_chunk_results) or 1
    )

    print(f"    📊 Mini-chunk Stats ({len(mini_chunk_results)} records):")
    print(f"       Status breakdown: {dict(statuses)}")
    print(
        f"       Findings - Policy: {findings_count['policy']} ({total_matches['policy']} matches), "
        f"Existence: {findings_count['existence']} ({total_matches['existence']} matches), "
        f"Notional: {findings_count['notional']} ({total_matches['notional']} matches), "
        f"PnL: {findings_count['pnl']} ({total_matches['pnl']} matches)"
    )
    print(f"       Avg processing time: {avg_duration:.2f}s")


def ping_server() -> Tuple[int, int]:
    """
    Pings the classification server's /info endpoint to dynamically configure
    MAX_WORKERS and BATCH_SIZE based on server GPU RAM.
    """
    print(f"Attempting to connect to server at {INFO_ENDPOINT}...")
    try:
        response = requests.get(INFO_ENDPOINT, timeout=10)
        response.raise_for_status()
        server_info = response.json()
        print("✅ Successfully connected to the classification server.")

        if server_info.get("gpu_available"):
            gpu_ram = server_info.get("total_ram_gb", 0)
            print(
                f"   -> Server has GPU: {server_info.get('gpu_name')} with {gpu_ram:.2f} GB RAM"
            )
            # Scale workers and batch size based on GPU RAM
            if gpu_ram > 20:  # A100, H100, etc.
                max_workers = 16
                batch_size = 128
            elif gpu_ram > 14:  # T4, P100, V100
                max_workers = 8
                batch_size = 64
            elif gpu_ram > 6:  # Smaller GPUs
                max_workers = 4
                batch_size = 32
            else:
                max_workers = 2
                batch_size = 16
        else:
            print("   -> ⚠️ Server has no GPU.")
            max_workers = 2
            batch_size = 16

        print(
            f"   -> Dynamically configured: MAX_WORKERS={max_workers}, BATCH_SIZE={batch_size}"
        )
        return max_workers, batch_size

    except requests.exceptions.RequestException as e:
        print(f"❌ Could not connect to server.")
        print(f"   Error: {e}")
        print("   Please ensure the classification server is running and accessible.")
        return MAX_WORKERS, BATCH_SIZE


# =============================================================================
# DATABASE FUNCTIONS
# =============================================================================


def setup_database():
    """Creates the results table in the database if it doesn't exist."""
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()

    # Build the CREATE TABLE statement with composite primary key
    # found_* fields now store JSON arrays of sentence indices
    columns = [
        "url TEXT",
        "cik INTEGER",
        "year INTEGER",
        "category TEXT",
        "status TEXT",
        "duration_s REAL",
        "error_message TEXT",
        "found_policy TEXT DEFAULT '[]'",
        "found_existence TEXT DEFAULT '[]'",
        "found_notional TEXT DEFAULT '[]'",
        "found_pnl TEXT DEFAULT '[]'",
        "PRIMARY KEY (url, category)",
    ]

    create_sql = f"CREATE TABLE IF NOT EXISTS {RESULTS_TABLE} ({', '.join(columns)})"
    c.execute(create_sql)
    c.execute(f"CREATE INDEX IF NOT EXISTS idx_res_url ON {RESULTS_TABLE} (url)")
    c.execute(
        f"CREATE INDEX IF NOT EXISTS idx_res_category ON {RESULTS_TABLE} (category)"
    )
    conn.commit()
    conn.close()


def get_unprocessed_filings(
    resumed_pairs: Optional[set] = None,
) -> List[Tuple[str, int, int]]:
    """
    Fetches filings from 'report_data' that are NOT yet fully processed in 'classification_results'.
    This makes the script resumable.
    Returns list of (url, cik, year) tuples.
    """
    if resumed_pairs is None:
        resumed_pairs = set()

    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()

    # Get (url, category) pairs already processed in the main DB table
    c.execute(f"SELECT url, category FROM {RESULTS_TABLE}")
    db_processed_pairs = set(c.fetchall())

    # Combine with pairs from a resumed parquet file
    all_processed_pairs = db_processed_pairs.union(resumed_pairs)

    # Fetch all filings from report_data
    query = """
        SELECT rd.url, rd.cik, rd.year
        FROM report_data rd
    """
    c.execute(query)
    all_filings = c.fetchall()
    conn.close()

    # Filter: keep filings that haven't been processed for all categories
    # A filing is "unprocessed" if it's missing any category result
    processed_urls = {pair[0] for pair in all_processed_pairs}
    filings = [f for f in all_filings if f[0] not in processed_urls]

    return filings


def get_sentences_for_filing(url: str) -> Dict[str, List[str]]:
    """
    Retrieves all categorized sentences for a given filing URL.
    """
    conn = sqlite3.connect(DB_PATH)
    c = conn.cursor()
    c.execute(
        "SELECT ir_matches, fx_matches, cp_matches, eq_matches FROM derivative_type_matches WHERE url=?",
        (url,),
    )
    result = c.fetchone()
    conn.close()

    if not result:
        return {}

    (ir_json, fx_json, cp_json, eq_json) = result
    sentences_by_type = {
        "ir_matches": json.loads(ir_json) if ir_json else [],
        "fx_matches": json.loads(fx_json) if fx_json else [],
        "cp_matches": json.loads(cp_json) if cp_json else [],
        "eq_matches": json.loads(eq_json) if eq_json else [],
    }
    return sentences_by_type


def iter_work_queue_from_db(filings: List[Tuple[str, int, int]]):
    """
    Generator that yields (url, cik, year, db_category, sentences) tuples.
    Lazily loads sentences only when needed, avoiding memory bloat.
    """
    for url, cik, year in filings:
        try:
            sentences_by_type = get_sentences_for_filing(url)
            for db_category, sentences in sentences_by_type.items():
                if sentences:  # Only yield if there are sentences
                    yield (url, cik, year, db_category, sentences)
        except Exception as e:
            print(f"[DEBUG] Error loading sentences for {url}: {e}")


# =============================================================================
# CLASSIFICATION WORKER
# =============================================================================


def classify_sentences_for_stage(
    sentences: List[str], term: str, year: int, stage: str
) -> Dict[str, List[int]]:
    """
    Sends a list of sentences to the classification server and checks for
    'entailment' for the hypotheses associated with that stage.

    Returns: A dictionary mapping hypothesis IDs to a list of indices of entailing sentences.
             Empty list if no entailment was found.
    """
    if not sentences:
        return {}

    # Initialize results for all hypotheses in this stage
    hypotheses_in_stage = STAGE_HYPOTHESES_MAP.get(stage, [])
    stage_results = {hypo_id: [] for hypo_id in hypotheses_in_stage}

    for batch_start in range(0, len(sentences), BATCH_SIZE):
        batch_end = min(batch_start + BATCH_SIZE, len(sentences))
        batch = sentences[batch_start:batch_end]

        payload = {
            "term": term,
            "stage": stage,
            "sentences": batch,
            "year": year,
        }
        try:
            response = requests.post(CLASSIFY_ENDPOINT, json=payload, timeout=180)
            response.raise_for_status()
            results = response.json().get("results", [])

            for local_idx, result in enumerate(results):
                global_idx = batch_start + local_idx
                classifications = result.get("classifications", {})
                for hypo_id in hypotheses_in_stage:
                    if classifications.get(hypo_id) == "entailment":
                        stage_results[hypo_id].append(global_idx)
        except requests.exceptions.RequestException as e:
            print(f"    ❌ API call failed for term '{term}': {e}")
            return {}  # Return empty dict on error

    return stage_results


def process_filing_category(
    filing_info: Tuple[str, int, int, str, List[str]],
) -> Dict[str, Any]:
    """
    Worker function to process a single filing-category pair with array-based findings.

    Returns a result dictionary with findings (as arrays of indices) and metadata.
    """
    url, cik, year, db_category, sentences = filing_info
    start_time = time.time()
    term = DERIVATIVE_TYPE_TO_TERM_MAP[db_category]
    category_short = CATEGORY_MAPPING[db_category]

    # Initialize result with all fields
    final_result: Dict[str, Any] = {
        "cik": cik,
        "year": year,
        "url": url,
        "category": category_short,
        "status": "processed",
        "error_message": "",
        "found_policy": [],
        "found_existence": [],
        "found_notional": [],
        "found_pnl": [],
    }

    try:
        if not sentences:
            final_result["status"] = "no_sentences"
            final_result["duration_s"] = round(time.time() - start_time, 2)
            return final_result

        # Stage 1: Notional
        notional_results = classify_sentences_for_stage(
            sentences, term, year, "notional"
        )
        if notional_results.get("H3_Notional", []):
            final_result["found_notional"] = notional_results["H3_Notional"]

        # Stage 2: Position & PnL
        position_results = classify_sentences_for_stage(
            sentences, term, year, "position"
        )
        if position_results.get("H2_Existence", []):
            final_result["found_existence"] = position_results["H2_Existence"]
        if position_results.get("H4_PnL_Impact", []):
            final_result["found_pnl"] = position_results["H4_PnL_Impact"]

        # Stage 3: Policy
        policy_results = classify_sentences_for_stage(sentences, term, year, "policy")
        if policy_results.get("H1_Policy", []):
            final_result["found_policy"] = policy_results["H1_Policy"]

        # Determine final summary status based on any findings
        if final_result["found_notional"]:
            final_result["status"] = "found_notional"
        elif final_result["found_existence"] or final_result["found_pnl"]:
            final_result["status"] = "found_position"
        elif final_result["found_policy"]:
            final_result["status"] = "found_policy_only"
        else:
            final_result["status"] = "no_evidence_found"

    except Exception as e:
        final_result["status"] = "error"
        final_result["error_message"] = str(e)

    final_result["duration_s"] = round(time.time() - start_time, 2)
    return final_result


# =============================================================================
# MAIN EXECUTION
# =============================================================================


def run_classification(total_chunks: int, chunk_index: int):
    """Main classification loop with mini-chunk processing and stats."""
    print("=" * 80)
    if total_chunks > 1:
        print(
            f"🚀 Starting DB Classification (Chunk Mode: {chunk_index}/{total_chunks})"
        )
    else:
        print("🚀 Starting DB Classification (Standalone Mode)")
    print("=" * 80)

    # Ping the server first to ensure it's available
    global MAX_WORKERS, BATCH_SIZE
    MAX_WORKERS, BATCH_SIZE = ping_server()
    if MAX_WORKERS == 0:  # Indicates a connection failure
        print("\nExiting due to server connection failure.")
        sys.exit(1)

    # 1. Define unique output file for this chunk
    output_parquet_file = RESULTS_PARQUET_TEMPLATE.format(chunk_index)

    # 2. Set up DB and handle resuming from Parquet file
    setup_database()
    parquet_processed_pairs, existing_results = get_already_processed_in_parquet(
        output_parquet_file
    )

    if existing_results:
        print(f"🔄 Resuming from existing file: {output_parquet_file}")
        print(f"   -> Loaded {len(existing_results)} results from checkpoint.")
        all_chunk_results = existing_results
    else:
        all_chunk_results = []

    # Get filings to process
    filings_to_process = get_unprocessed_filings(resumed_pairs=parquet_processed_pairs)

    if not filings_to_process:
        print("✅ No new filings to process. Exiting.")
        sys.exit(0)

    # 3. Split workload for multi-machine processing
    if total_chunks > 1:
        print(f"Found {len(filings_to_process)} total unprocessed filings.")
        num_reports = len(filings_to_process)
        chunk_size = (num_reports + total_chunks - 1) // total_chunks
        start_index = chunk_index * chunk_size
        end_index = start_index + chunk_size
        filings_to_process = filings_to_process[start_index:end_index]
        print(
            f"   -> This machine's workload: {len(filings_to_process)} filings (index {start_index} to {end_index})."
        )

    if not filings_to_process:
        print("✅ No new filings for this chunk to process. Exiting.")
        sys.exit(0)

    total_processed = 0
    total_positive = 0
    last_drive_save_time = time.time()
    results_since_last_save = 0
    start_time = time.time()

    # Create a generator for the work queue (lazy loading)
    work_queue_generator = iter_work_queue_from_db(filings_to_process)

    print(f"\nProcessing filing-category pairs with lazy loading...")
    print("=" * 80)

    # 4. Process work items in mini-chunks sequentially
    mini_chunk_idx = 0
    while True:
        mini_chunk_idx += 1
        mini_chunk = []
        mini_chunk_start = time.time()
        mini_chunk_results = []
        
        # Collect up to SAVE_INTERVAL_FILINGS items from the generator
        for _ in range(SAVE_INTERVAL_FILINGS):
            try:
                work_item = next(work_queue_generator)
                mini_chunk.append(work_item)
            except StopIteration:
                break

        if not mini_chunk:
            break  # No more items to process

        print(f"\n📦 Mini-chunk {mini_chunk_idx} ({len(mini_chunk)} pairs)")

        # Process this mini-chunk with threading
        try:
            with ThreadPoolExecutor(max_workers=MAX_WORKERS) as executor:
                future_to_work = {
                    executor.submit(process_filing_category, work): work
                    for work in mini_chunk
                }

                for future in tqdm(
                    as_completed(future_to_work),
                    total=len(mini_chunk),
                    desc="   Processing",
                    leave=False,
                ):
                    try:
                        result = future.result()
                        if result:
                            all_chunk_results.append(result)
                            mini_chunk_results.append(result)
                            total_processed += 1
                            # Check if any finding was made (any found_* array with len > 0)
                            if any(
                                len(result.get(f"found_{f_type}", [])) > 0
                                for f_type in ["policy", "existence", "notional", "pnl"]
                            ):
                                total_positive += 1

                    except Exception as e:
                        work = future_to_work[future]
                        print(f"   ❌ Error processing {work[0]}: {e}")

        except KeyboardInterrupt:
            print("\n🛑 Process interrupted by user. Saving pending results...")

        # Print mini-chunk statistics
        print_mini_chunk_stats(mini_chunk_results)
        mini_chunk_time = time.time() - mini_chunk_start
        print(f"   ⏱️  Mini-chunk time: {format_time(mini_chunk_time)}")

        # Save intermediate checkpoint every N filings
        if len(all_chunk_results) % SAVE_INTERVAL_FILINGS == 0:
            saved_count = save_chunk_to_parquet(all_chunk_results, output_parquet_file)
            print(f"   💾 Checkpoint saved: {saved_count} total results")
            results_since_last_save = 0

        # Periodic Google Drive backup
        time_since_last_save = time.time() - last_drive_save_time
        if IS_COLAB and (
            time_since_last_save >= DRIVE_SAVE_INTERVAL_SECONDS
            or results_since_last_save >= DRIVE_SAVE_INTERVAL_RESULTS
        ):
            print(f"   ☁️ Backing up to Google Drive...")
            backup_to_drive(output_parquet_file)
            last_drive_save_time = time.time()
            results_since_last_save = 0

        results_since_last_save += len(mini_chunk_results)

    # 5. Final save for any remaining results
    if all_chunk_results:
        print(f"\n💾 Saving final results for this chunk...")
        saved_count = save_chunk_to_parquet(all_chunk_results, output_parquet_file)
        print(f"   -> Saved {saved_count} total records to {output_parquet_file}.")

    # 6. Final backup to Google Drive
    if IS_COLAB and Path(output_parquet_file).exists():
        print(f"\n☁️ Final backup to Google Drive...")
        backup_to_drive(output_parquet_file)

    # 7. Print summary
    total_time = time.time() - start_time
    print("\n" + "=" * 80)
    print("✅ CLASSIFICATION COMPLETE")
    print("=" * 80)
    print(f"Total filing-category pairs processed: {total_processed:,}")
    print(f"Pairs with any evidence found: {total_positive:,}")
    if total_processed > 0:
        print(f"Evidence rate: {(total_positive / total_processed * 100):.1f}%")
        print(f"Total time: {format_time(total_time)}")
        print(f"Avg time per pair: {(total_time / total_processed):.2f}s")

    print(f"💾 Results saved to '{output_parquet_file}'")
    if total_chunks > 1:
        print(f"ℹ️  Remember to merge all chunk files when processing is complete.")
    print("\n✨ Done!")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Run the database-driven classification client in standalone or chunked mode."
    )
    parser.add_argument(
        "--total-chunks",
        type=int,
        default=1,
        help="Total number of chunks to split the workload into.",
    )
    parser.add_argument(
        "--chunk-index",
        type=int,
        default=0,
        help="The 0-based index of the chunk this instance should process.",
    )
    args = parser.parse_args()

    if not (0 <= args.chunk_index < args.total_chunks):
        print("❌ Error: --chunk-index must be between 0 and --total-chunks-1.")
        sys.exit(1)

    run_classification(args.total_chunks, args.chunk_index)
