from enum import Enum

class Specificity(Enum):
    EXPLICIT = "EXPLICIT"
    INHERITED = "INHERITED_PREV"
    INFERRED_UNION = "INFERRED_UNION"
    INFERRED_LANG = "INFERRED_LANGUAGE"
    EXPLICIT_INFERRED = "INFERRED_EXPLICIT"
    IMPLICIT = "IMPLICIT"
    UNKNOWN = "UNKNOWN"


class CoverageType(Enum):
    NONE = "NONE"
    EXPLICIT_PERCENT = "EXPLICIT_PERCENT"
    CALCULATED = "CALCULATED_FROM_COUNTS"
    QUALITATIVE = "QUALITATIVE"
    REMAINING = "REMAINING"
    UNION_CONTEXT = "UNION_CONTEXT"

class SourceType(Enum):
    EXPLICIT = "EXPLICIT"
    CALCULATED = "CALCULATED"
    INFERRED = "INFERRED"
    VIRTUAL_POOL = "VIRTUAL_POOL"
    WEIGHTED_DIVISION = "WEIGHTED_DIVISION"
    FALLBACK = "FALLBACK"
    INHERITED = "INHERITED"
    UNKNOWN = "UNKNOWN"


class PercentageSourceDetail(Enum):
    EXPLICIT_PERCENTAGE = "EXPLICIT_PERCENTAGE"
    CALCULATED_PERCENTAGE = "CALCULATED_PERCENTAGE"
    REMAINING_STATEMENT = "REMAINING_STATEMENT"
    QUALITATIVE_INFERRED_PERCENTAGE = "QUALITATIVE_INFERRED_PERCENTAGE"
    UNION_CONTEXT_ONLY = "UNION_CONTEXT_ONLY"
    CALCULATED_ZERO_FROM_GAP_FIX = "CALCULATED_ZERO_FROM_GAP_FIX"
    CALCULATED_FROM_COUNTS = "CALCULATED_FROM_COUNTS"
    CALCULATED_FROM_REMAINING_GAP = "CALCULATED_FROM_REMAINING_GAP"
    AGGREGATE_PROPAGATION = "AGGREGATE_PROPAGATION"
    INFERRED_ZERO_FROM_PLACEHOLDER = "INFERRED_ZERO_FROM_PLACEHOLDER"
    INFERRED_ZERO_FROM_CENSUS_ONLY = "INFERRED_ZERO_FROM_CENSUS_ONLY"
    INFERRED_ZERO_FROM_REGION_TOTAL_ONLY = "INFERRED_ZERO_FROM_REGION_TOTAL_ONLY"
    DUMMY_INFERRED_REGION_WEIGHTED = "DUMMY_INFERRED_REGION_WEIGHTED"
    DUMMY_INFERRED_EXTERNAL_DATA = "DUMMY_INFERRED_EXTERNAL_DATA"
    DUMMY_INFERRED_DEFAULT_RATE = "DUMMY_INFERRED_DEFAULT_RATE"
    FALLBACK_NEGATION_GUARD_ZERO = "FALLBACK_NEGATION_GUARD_ZERO"


class CountSourceDetail(Enum):
    EXPLICIT_COVERED_COUNT = "EXPLICIT_COVERED_COUNT"
    EXPLICIT_NOT_COVERED_COUNT = "EXPLICIT_NOT_COVERED_COUNT"
    SPLIT_ALLOCATED_COVERED_COUNT = "SPLIT_ALLOCATED_COVERED_COUNT"
    CALCULATED_FROM_TOTAL_MINUS_NOT_COVERED = "CALCULATED_FROM_TOTAL_MINUS_NOT_COVERED"
    CALCULATED_FROM_TOTAL_MINUS_COVERED = "CALCULATED_FROM_TOTAL_MINUS_COVERED"
    CALCULATED_FROM_PERCENTAGE_AND_TOTAL = "CALCULATED_FROM_PERCENTAGE_AND_TOTAL"
    CALCULATED_FROM_PERCENTAGE_AND_CENSUS_TOTAL = "CALCULATED_FROM_PERCENTAGE_AND_CENSUS_TOTAL"
    CALCULATED_FROM_PERCENTAGE_AND_FALLBACK_DENOMINATOR = "CALCULATED_FROM_PERCENTAGE_AND_FALLBACK_DENOMINATOR"
    INFERRED_FROM_DUMMY_PERCENTAGE = "INFERRED_FROM_DUMMY_PERCENTAGE"
    INFERRED_FROM_INFERRED_PERCENTAGE = "INFERRED_FROM_INFERRED_PERCENTAGE"
    REMAINING_GAP_FILL = "REMAINING_GAP_FILL"
    REMAINING_GAP_FILL_ZERO = "REMAINING_GAP_FILL_ZERO"
    INFERRED_ZERO_FROM_PLACEHOLDER = "INFERRED_ZERO_FROM_PLACEHOLDER"
    INFERRED_ZERO_FROM_CENSUS_ONLY = "INFERRED_ZERO_FROM_CENSUS_ONLY"
    INFERRED_ZERO_FROM_REGION_TOTAL_ONLY = "INFERRED_ZERO_FROM_REGION_TOTAL_ONLY"
    FALLBACK_NEGATION_GUARD_ZERO = "FALLBACK_NEGATION_GUARD_ZERO"
    EXPLICIT_BARGAINING_UNIT_COUNT = "EXPLICIT_BARGAINING_UNIT_COUNT"


class TotalSourceDetail(Enum):
    EXPLICIT_SCOPE_TOTAL = "EXPLICIT_SCOPE_TOTAL"
    SPLIT_SCOPE_TOTAL = "SPLIT_SCOPE_TOTAL"
    CENSUS_GAP_FIX = "CENSUS_GAP_FIX"
    CENSUS_UPGRADE = "CENSUS_UPGRADE"
    INHERITED_FROM_CENSUS_TOTAL = "INHERITED_FROM_CENSUS_TOTAL"
    REMAINING_GAP_FILL = "REMAINING_GAP_FILL"
    COUNTRY_CENSUS_BACKFILL = "COUNTRY_CENSUS_BACKFILL"
    COUNTRY_CENSUS_UPDATE = "COUNTRY_CENSUS_UPDATE"
    COUNTRY_CENSUS_ONLY = "COUNTRY_CENSUS_ONLY"
    REGION_TOTAL_ONLY = "REGION_TOTAL_ONLY"
    WEIGHTED_DIVISION_VIRTUAL_POOL = "WEIGHTED_DIVISION_VIRTUAL_POOL"
    FALLBACK_DENOMINATOR_COUNTRY = "FALLBACK_DENOMINATOR_COUNTRY"
    FALLBACK_DENOMINATOR_REGION = "FALLBACK_DENOMINATOR_REGION"
    FALLBACK_DENOMINATOR_GLOBAL = "FALLBACK_DENOMINATOR_GLOBAL"


class DenominatorSourceDetail(Enum):
    EXPLICIT_SCOPE_TOTAL = "EXPLICIT_SCOPE_TOTAL"
    SPLIT_SCOPE_TOTAL = "SPLIT_SCOPE_TOTAL"
    CENSUS_UPGRADE = "CENSUS_UPGRADE"
    INHERITED_FROM_CENSUS_TOTAL = "INHERITED_FROM_CENSUS_TOTAL"
    REMAINING_GAP_FILL = "REMAINING_GAP_FILL"
    EXISTING_TOTAL = "EXISTING_TOTAL"
    EXISTING_TOTAL_AFTER_AGGREGATE_PROPAGATION = "EXISTING_TOTAL_AFTER_AGGREGATE_PROPAGATION"
    COUNTRY_CENSUS_BACKFILL = "COUNTRY_CENSUS_BACKFILL"
    COUNTRY_CENSUS_UPDATE = "COUNTRY_CENSUS_UPDATE"
    COUNTRY_CENSUS_ONLY = "COUNTRY_CENSUS_ONLY"
    REGION_TOTAL_ONLY = "REGION_TOTAL_ONLY"
    WEIGHTED_DIVISION_VIRTUAL_POOL = "WEIGHTED_DIVISION_VIRTUAL_POOL"
    FALLBACK_DENOMINATOR_COUNTRY = "FALLBACK_DENOMINATOR_COUNTRY"
    FALLBACK_DENOMINATOR_REGION = "FALLBACK_DENOMINATOR_REGION"
    FALLBACK_DENOMINATOR_GLOBAL = "FALLBACK_DENOMINATOR_GLOBAL"

class PercentageQualifier(Enum):
    NONE = "NONE"
    RANGE = "RANGE"
    CALC_ERROR = "CALC_ERROR"

class NegationType(Enum):
    NOT_COVERED = "NOT_COVERED"
    ZERO_COVERAGE = "ZERO_COVERAGE"
    QUALITATIVE_ZERO = "QUALITATIVE_ZERO"

class TemporalScope(Enum):
    CURRENT = "CURRENT"
    FUTURE = "FUTURE"
    HISTORICAL = "HISTORICAL"
    CONDITIONAL = "CONDITIONAL"

class RiskType(Enum):
    LABOR_RISK = "LABOR_RISK"
    UNION_RISK = "UNION_RISK"

class RiskSignalType(Enum):
    RISK_EVENT = "RISK_EVENT"
    LEGAL_REQUIREMENT = "LEGAL_REQUIREMENT"
    BOILERPLATE = "BOILERPLATE"
    RELATIONSHIP_CONTEXT = "RELATIONSHIP_CONTEXT"
    OTHER_CONTEXT = "OTHER_CONTEXT"
    ACTUAL = "ACTUAL"
    UNKNOWN = "UNKNOWN"
    POTENTIAL = "POTENTIAL"

class RelationshipStatus(Enum):
    POSITIVE = "POSITIVE"
    NEUTRAL = "NEUTRAL"
    NEGATIVE = "NEGATIVE"
    UNKNOWN = "UNKNOWN"

def load_details_source():
    detail_map: dict[str, str] = {}
    for _detail in (
        PercentageSourceDetail.EXPLICIT_PERCENTAGE,
        CountSourceDetail.EXPLICIT_COVERED_COUNT,
        CountSourceDetail.EXPLICIT_NOT_COVERED_COUNT,
        CountSourceDetail.EXPLICIT_BARGAINING_UNIT_COUNT,
        TotalSourceDetail.EXPLICIT_SCOPE_TOTAL,
        DenominatorSourceDetail.EXPLICIT_SCOPE_TOTAL,
        DenominatorSourceDetail.CENSUS_UPGRADE,
    ):
        detail_map[_detail.value] = SourceType.EXPLICIT.value

    for _detail in (
        PercentageSourceDetail.CALCULATED_PERCENTAGE,
        PercentageSourceDetail.CALCULATED_ZERO_FROM_GAP_FIX,
        PercentageSourceDetail.CALCULATED_FROM_COUNTS,
        PercentageSourceDetail.CALCULATED_FROM_REMAINING_GAP,
        PercentageSourceDetail.AGGREGATE_PROPAGATION,
        CountSourceDetail.CALCULATED_FROM_TOTAL_MINUS_NOT_COVERED,
        CountSourceDetail.CALCULATED_FROM_TOTAL_MINUS_COVERED,
        CountSourceDetail.CALCULATED_FROM_PERCENTAGE_AND_TOTAL,
        CountSourceDetail.CALCULATED_FROM_PERCENTAGE_AND_CENSUS_TOTAL,
        CountSourceDetail.REMAINING_GAP_FILL,
        CountSourceDetail.REMAINING_GAP_FILL_ZERO,
        TotalSourceDetail.CENSUS_GAP_FIX,
        TotalSourceDetail.CENSUS_UPGRADE,
        TotalSourceDetail.INHERITED_FROM_CENSUS_TOTAL,
        TotalSourceDetail.REMAINING_GAP_FILL,
        DenominatorSourceDetail.INHERITED_FROM_CENSUS_TOTAL,
    ):
        detail_map[_detail.value] = SourceType.CALCULATED.value

    for _detail in (
        PercentageSourceDetail.QUALITATIVE_INFERRED_PERCENTAGE,
        PercentageSourceDetail.UNION_CONTEXT_ONLY,
        PercentageSourceDetail.INFERRED_ZERO_FROM_PLACEHOLDER,
        PercentageSourceDetail.INFERRED_ZERO_FROM_CENSUS_ONLY,
        PercentageSourceDetail.INFERRED_ZERO_FROM_REGION_TOTAL_ONLY,
        PercentageSourceDetail.DUMMY_INFERRED_REGION_WEIGHTED,
        PercentageSourceDetail.DUMMY_INFERRED_EXTERNAL_DATA,
        PercentageSourceDetail.DUMMY_INFERRED_DEFAULT_RATE,
        CountSourceDetail.INFERRED_ZERO_FROM_PLACEHOLDER,
        CountSourceDetail.INFERRED_ZERO_FROM_CENSUS_ONLY,
        CountSourceDetail.INFERRED_ZERO_FROM_REGION_TOTAL_ONLY,
        CountSourceDetail.INFERRED_FROM_DUMMY_PERCENTAGE,
        CountSourceDetail.INFERRED_FROM_INFERRED_PERCENTAGE,
        TotalSourceDetail.COUNTRY_CENSUS_ONLY,
        TotalSourceDetail.REGION_TOTAL_ONLY,
        DenominatorSourceDetail.COUNTRY_CENSUS_ONLY,
        DenominatorSourceDetail.REGION_TOTAL_ONLY,
    ):
        detail_map[_detail.value] = SourceType.INFERRED.value

    for _detail in (
        CountSourceDetail.SPLIT_ALLOCATED_COVERED_COUNT,
    ):
        detail_map[_detail.value] = SourceType.WEIGHTED_DIVISION.value

    for _detail in (
        TotalSourceDetail.WEIGHTED_DIVISION_VIRTUAL_POOL,
        DenominatorSourceDetail.WEIGHTED_DIVISION_VIRTUAL_POOL,
    ):
        detail_map[_detail.value] = SourceType.VIRTUAL_POOL.value

    for _detail in (
        PercentageSourceDetail.FALLBACK_NEGATION_GUARD_ZERO,
        CountSourceDetail.FALLBACK_NEGATION_GUARD_ZERO,
        CountSourceDetail.CALCULATED_FROM_PERCENTAGE_AND_FALLBACK_DENOMINATOR,
        TotalSourceDetail.FALLBACK_DENOMINATOR_COUNTRY,
        TotalSourceDetail.FALLBACK_DENOMINATOR_REGION,
        TotalSourceDetail.FALLBACK_DENOMINATOR_GLOBAL,
        DenominatorSourceDetail.FALLBACK_DENOMINATOR_COUNTRY,
        DenominatorSourceDetail.FALLBACK_DENOMINATOR_REGION,
        DenominatorSourceDetail.FALLBACK_DENOMINATOR_GLOBAL,
    ):
        detail_map[_detail.value] = SourceType.FALLBACK.value

    for _detail in (
        TotalSourceDetail.COUNTRY_CENSUS_BACKFILL,
        TotalSourceDetail.COUNTRY_CENSUS_UPDATE,
        DenominatorSourceDetail.COUNTRY_CENSUS_BACKFILL,
        DenominatorSourceDetail.COUNTRY_CENSUS_UPDATE,
    ):
        detail_map[_detail.value] = SourceType.INHERITED.value
    return detail_map

DETAIL_TO_SOURCE_TYPE = load_details_source()
