from enum import Enum

class Specificity(Enum):
    EXPLICIT = "explicit"
    INHERITED = "INHERITED_PREV"
    INFERRED_UNION = "INFERRED_UNION"
    INFERRED_LANG = "INFERRED_LANGUAGE"
    EXPLICIT_INFERRED = "INFERRED_EXPLICIT"
    IMPLICIT = "IMPLICIT"
    UNKNOWN = "UNKNOWN"


class CoverageType(Enum):
    EXPLICIT_PERCENT = "EXPLICIT_PERCENT"
    CALCULATED = "CALCULATED_FROM_COUNTS"
    QUALITATIVE = "QUALITATIVE"

class PercentageQualifier(Enum):
    SIGNIFICANT = "SIGNIFICANT"
    MAJORITY = "MAJORITY"
    PORTION = "PORTION"
    SUBSTANTIAL = "SUBSTANTIAL"
    SUBSTANTIALLY_ALL = "SUBSTANTIALLY_ALL"
    UNSPECIFIED = "UNSPECIFIED"
    NONE = "NONE"

class NegationType(Enum):
    NOT_COVERED = "NOT_COVERED"
    ZERO_COVERAGE = "ZERO_COVERAGE"
    QUALITATIVE_ZERO = "QUALITATIVE_ZERO"

class TemporalScope(Enum):
    CURRENT = "CURRENT"
    FUTURE = "FUTURE"
    FUTURE_EXPECTED = "FUTURE_EXPECTED"
    CONDITIONAL = "CONDITIONAL"

class RiskType(Enum):
    LABOR_RISK = "LABOR_RISK"
    UNION_RISK = "UNION_RISK"