from enum import Enum

class Specificity(Enum):
    EXPLICIT = "EXPLICIT"
    INHERITED = "INHERITED_PREV"
    INFERRED_UNION = "INFERRED_UNION"
    INFERRED_LANG = "INFERRED_LANGUAGE"
    EXPLICIT_INFERRED = "INFERRED_EXPLICIT"
    IMPLICIT = "IMPLICIT"
    UNKNOWN = "UNKNOWN"


class CoverageType(Enum):
    NONE = "NONE"
    EXPLICIT_PERCENT = "EXPLICIT_PERCENT"
    CALCULATED = "CALCULATED_FROM_COUNTS"
    QUALITATIVE = "QUALITATIVE"
    REMAINING = "REMAINING"
    UNION_CONTEXT = "UNION_CONTEXT"

class SourceType(Enum):
    EXPLICIT = "EXPLICIT"
    CALCULATED = "CALCULATED"
    INFERRED = "INFERRED"
    WEIGHTED_DIVISION = "WEIGHTED_DIVISION"
    FALLBACK = "FALLBACK"
    INHERITED = "INHERITED"
    UNKNOWN = "UNKNOWN"


class PercentageSourceDetail(Enum):
    EXPLICIT_PERCENTAGE = "EXPLICIT_PERCENTAGE"
    CALCULATED_PERCENTAGE = "CALCULATED_PERCENTAGE"
    REMAINING_STATEMENT = "REMAINING_STATEMENT"
    QUALITATIVE_INFERRED_PERCENTAGE = "QUALITATIVE_INFERRED_PERCENTAGE"
    UNION_CONTEXT_ONLY = "UNION_CONTEXT_ONLY"
    CALCULATED_ZERO_FROM_GAP_FIX = "CALCULATED_ZERO_FROM_GAP_FIX"
    CALCULATED_FROM_COUNTS = "CALCULATED_FROM_COUNTS"
    CALCULATED_FROM_REMAINING_GAP = "CALCULATED_FROM_REMAINING_GAP"
    AGGREGATE_PROPAGATION = "AGGREGATE_PROPAGATION"
    INFERRED_ZERO_FROM_PLACEHOLDER = "INFERRED_ZERO_FROM_PLACEHOLDER"
    INFERRED_ZERO_FROM_CENSUS_ONLY = "INFERRED_ZERO_FROM_CENSUS_ONLY"
    INFERRED_ZERO_FROM_REGION_TOTAL_ONLY = "INFERRED_ZERO_FROM_REGION_TOTAL_ONLY"
    DUMMY_INFERRED_REGION_WEIGHTED = "DUMMY_INFERRED_REGION_WEIGHTED"
    DUMMY_INFERRED_EXTERNAL_DATA = "DUMMY_INFERRED_EXTERNAL_DATA"
    DUMMY_INFERRED_DEFAULT_RATE = "DUMMY_INFERRED_DEFAULT_RATE"
    FALLBACK_NEGATION_GUARD_ZERO = "FALLBACK_NEGATION_GUARD_ZERO"


class CountSourceDetail(Enum):
    EXPLICIT_COVERED_COUNT = "EXPLICIT_COVERED_COUNT"
    EXPLICIT_NOT_COVERED_COUNT = "EXPLICIT_NOT_COVERED_COUNT"
    SPLIT_ALLOCATED_COVERED_COUNT = "SPLIT_ALLOCATED_COVERED_COUNT"
    CALCULATED_FROM_TOTAL_MINUS_NOT_COVERED = "CALCULATED_FROM_TOTAL_MINUS_NOT_COVERED"
    CALCULATED_FROM_TOTAL_MINUS_COVERED = "CALCULATED_FROM_TOTAL_MINUS_COVERED"
    CALCULATED_FROM_PERCENTAGE_AND_TOTAL = "CALCULATED_FROM_PERCENTAGE_AND_TOTAL"
    CALCULATED_FROM_PERCENTAGE_AND_CENSUS_TOTAL = "CALCULATED_FROM_PERCENTAGE_AND_CENSUS_TOTAL"
    CALCULATED_FROM_PERCENTAGE_AND_FALLBACK_DENOMINATOR = "CALCULATED_FROM_PERCENTAGE_AND_FALLBACK_DENOMINATOR"
    REMAINING_GAP_FILL = "REMAINING_GAP_FILL"
    REMAINING_GAP_FILL_ZERO = "REMAINING_GAP_FILL_ZERO"
    INFERRED_ZERO_FROM_PLACEHOLDER = "INFERRED_ZERO_FROM_PLACEHOLDER"
    INFERRED_ZERO_FROM_CENSUS_ONLY = "INFERRED_ZERO_FROM_CENSUS_ONLY"
    INFERRED_ZERO_FROM_REGION_TOTAL_ONLY = "INFERRED_ZERO_FROM_REGION_TOTAL_ONLY"
    FALLBACK_NEGATION_GUARD_ZERO = "FALLBACK_NEGATION_GUARD_ZERO"


class TotalSourceDetail(Enum):
    EXPLICIT_SCOPE_TOTAL = "EXPLICIT_SCOPE_TOTAL"
    SPLIT_SCOPE_TOTAL = "SPLIT_SCOPE_TOTAL"
    CENSUS_GAP_FIX = "CENSUS_GAP_FIX"
    CENSUS_UPGRADE = "CENSUS_UPGRADE"
    INHERITED_FROM_CENSUS_TOTAL = "INHERITED_FROM_CENSUS_TOTAL"
    REMAINING_GAP_FILL = "REMAINING_GAP_FILL"
    COUNTRY_CENSUS_BACKFILL = "COUNTRY_CENSUS_BACKFILL"
    COUNTRY_CENSUS_UPDATE = "COUNTRY_CENSUS_UPDATE"
    COUNTRY_CENSUS_ONLY = "COUNTRY_CENSUS_ONLY"
    REGION_TOTAL_ONLY = "REGION_TOTAL_ONLY"
    WEIGHTED_DIVISION_VIRTUAL_POOL = "WEIGHTED_DIVISION_VIRTUAL_POOL"
    FALLBACK_DENOMINATOR_COUNTRY = "FALLBACK_DENOMINATOR_COUNTRY"
    FALLBACK_DENOMINATOR_REGION = "FALLBACK_DENOMINATOR_REGION"
    FALLBACK_DENOMINATOR_GLOBAL = "FALLBACK_DENOMINATOR_GLOBAL"


class DenominatorSourceDetail(Enum):
    EXPLICIT_SCOPE_TOTAL = "EXPLICIT_SCOPE_TOTAL"
    SPLIT_SCOPE_TOTAL = "SPLIT_SCOPE_TOTAL"
    CENSUS_UPGRADE = "CENSUS_UPGRADE"
    INHERITED_FROM_CENSUS_TOTAL = "INHERITED_FROM_CENSUS_TOTAL"
    REMAINING_GAP_FILL = "REMAINING_GAP_FILL"
    EXISTING_TOTAL = "EXISTING_TOTAL"
    EXISTING_TOTAL_AFTER_AGGREGATE_PROPAGATION = "EXISTING_TOTAL_AFTER_AGGREGATE_PROPAGATION"
    COUNTRY_CENSUS_BACKFILL = "COUNTRY_CENSUS_BACKFILL"
    COUNTRY_CENSUS_UPDATE = "COUNTRY_CENSUS_UPDATE"
    COUNTRY_CENSUS_ONLY = "COUNTRY_CENSUS_ONLY"
    REGION_TOTAL_ONLY = "REGION_TOTAL_ONLY"
    WEIGHTED_DIVISION_VIRTUAL_POOL = "WEIGHTED_DIVISION_VIRTUAL_POOL"
    FALLBACK_DENOMINATOR_COUNTRY = "FALLBACK_DENOMINATOR_COUNTRY"
    FALLBACK_DENOMINATOR_REGION = "FALLBACK_DENOMINATOR_REGION"
    FALLBACK_DENOMINATOR_GLOBAL = "FALLBACK_DENOMINATOR_GLOBAL"

class PercentageQualifier(Enum):
    NONE = "NONE"
    RANGE = "RANGE"
    CALC_ERROR = "CALC_ERROR"

class NegationType(Enum):
    NOT_COVERED = "NOT_COVERED"
    ZERO_COVERAGE = "ZERO_COVERAGE"
    QUALITATIVE_ZERO = "QUALITATIVE_ZERO"

class TemporalScope(Enum):
    CURRENT = "CURRENT"
    FUTURE = "FUTURE"
    HISTORICAL = "HISTORICAL"
    CONDITIONAL = "CONDITIONAL"

class RiskType(Enum):
    LABOR_RISK = "LABOR_RISK"
    UNION_RISK = "UNION_RISK"

class RelationshipStatus(Enum):
    POSITIVE = "POSITIVE"
    NEUTRAL = "NEUTRAL"
    NEGATIVE = "NEGATIVE"
    UNKNOWN = "UNKNOWN"
