debts = [
    # --- Corporate & Bank Debt ---
    "term loans",
    "revolving credit facility",
    "bridge loans",
    "syndicated loans",
    "bilateral loans",
    "club loans",
    "asset-based lending (ABL)",
    "equipment financing",
    "working capital loans",
    "project finance loans",
    "acquisition financing",
    "mezzanine debt",
    "venture debt",
    "subordinated debt",
    "senior secured debt",
    "senior unsecured debt",
    "convertible debt",
    "private placement notes",
    # --- Marketable Securities (Bonds & Notes) ---
    "corporate bonds",
    "government bonds",
    "municipal bonds",
    "agency bonds",
    "zero-coupon bonds",
    "perpetual bonds",
    "callable bonds",
    "puttable bonds",
    "fixed-rate bonds",
    "floating-rate bonds",
    "inflation-indexed bonds",
    "convertible bonds",
    "secured bonds",
    "unsecured bonds",
    "debentures",
    # --- International Bonds ---
    "eurobonds",
    # --- Short-Term & Money Market Instruments ---
    "commercial paper",
    "certificates of deposit (CDs)",
    "banker's acceptances",
    "repurchase agreements (repos)",
    "federal funds",
    "money market instruments",
    "eurodollar borrowings",
    # --- Asset-Backed & Structured Finance ---
    "asset-backed securities (ABS)",
    "mortgage-backed securities (MBS)",
    "commercial mortgage-backed securities (CMBS)",
    "collateralized loan obligations (CLOs)",
    "factoring",
    "supply chain finance",
    "trade finance",
    # --- Financing & Consumer Loans ---
    "residential mortgages",
    "commercial mortgages",
    "home equity lines of credit (HELOCs)",
    "real estate loans",
    "construction loans",
    "development loans",
    "mortgage loans"
    # --- Other / Hybrid ---
    "lease obligations",
    "capital lease liabilities",
    "convertible preferred shares",
    "credit agreement",
]
